// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/freedom/config.proto

package com.v2ray.core.proxy.freedom;

/**
 * Protobuf type {@code v2ray.core.proxy.freedom.DestinationOverride}
 */
public  final class DestinationOverride extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.proxy.freedom.DestinationOverride)
    DestinationOverrideOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DestinationOverride.newBuilder() to construct.
  private DestinationOverride(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DestinationOverride() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DestinationOverride(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.v2ray.core.common.protocol.ServerEndpoint.Builder subBuilder = null;
            if (server_ != null) {
              subBuilder = server_.toBuilder();
            }
            server_ = input.readMessage(com.v2ray.core.common.protocol.ServerEndpoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(server_);
              server_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.proxy.freedom.ConfigOuterClass.internal_static_v2ray_core_proxy_freedom_DestinationOverride_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.proxy.freedom.ConfigOuterClass.internal_static_v2ray_core_proxy_freedom_DestinationOverride_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.proxy.freedom.DestinationOverride.class, com.v2ray.core.proxy.freedom.DestinationOverride.Builder.class);
  }

  public static final int SERVER_FIELD_NUMBER = 1;
  private com.v2ray.core.common.protocol.ServerEndpoint server_;
  /**
   * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
   */
  public boolean hasServer() {
    return server_ != null;
  }
  /**
   * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
   */
  public com.v2ray.core.common.protocol.ServerEndpoint getServer() {
    return server_ == null ? com.v2ray.core.common.protocol.ServerEndpoint.getDefaultInstance() : server_;
  }
  /**
   * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
   */
  public com.v2ray.core.common.protocol.ServerEndpointOrBuilder getServerOrBuilder() {
    return getServer();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (server_ != null) {
      output.writeMessage(1, getServer());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (server_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getServer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.proxy.freedom.DestinationOverride)) {
      return super.equals(obj);
    }
    com.v2ray.core.proxy.freedom.DestinationOverride other = (com.v2ray.core.proxy.freedom.DestinationOverride) obj;

    boolean result = true;
    result = result && (hasServer() == other.hasServer());
    if (hasServer()) {
      result = result && getServer()
          .equals(other.getServer());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasServer()) {
      hash = (37 * hash) + SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getServer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.freedom.DestinationOverride parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.proxy.freedom.DestinationOverride prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.freedom.DestinationOverride}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.freedom.DestinationOverride)
      com.v2ray.core.proxy.freedom.DestinationOverrideOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.freedom.ConfigOuterClass.internal_static_v2ray_core_proxy_freedom_DestinationOverride_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.freedom.ConfigOuterClass.internal_static_v2ray_core_proxy_freedom_DestinationOverride_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.freedom.DestinationOverride.class, com.v2ray.core.proxy.freedom.DestinationOverride.Builder.class);
    }

    // Construct using com.v2ray.core.proxy.freedom.DestinationOverride.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (serverBuilder_ == null) {
        server_ = null;
      } else {
        server_ = null;
        serverBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.proxy.freedom.ConfigOuterClass.internal_static_v2ray_core_proxy_freedom_DestinationOverride_descriptor;
    }

    public com.v2ray.core.proxy.freedom.DestinationOverride getDefaultInstanceForType() {
      return com.v2ray.core.proxy.freedom.DestinationOverride.getDefaultInstance();
    }

    public com.v2ray.core.proxy.freedom.DestinationOverride build() {
      com.v2ray.core.proxy.freedom.DestinationOverride result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.v2ray.core.proxy.freedom.DestinationOverride buildPartial() {
      com.v2ray.core.proxy.freedom.DestinationOverride result = new com.v2ray.core.proxy.freedom.DestinationOverride(this);
      if (serverBuilder_ == null) {
        result.server_ = server_;
      } else {
        result.server_ = serverBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.proxy.freedom.DestinationOverride) {
        return mergeFrom((com.v2ray.core.proxy.freedom.DestinationOverride)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.proxy.freedom.DestinationOverride other) {
      if (other == com.v2ray.core.proxy.freedom.DestinationOverride.getDefaultInstance()) return this;
      if (other.hasServer()) {
        mergeServer(other.getServer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.v2ray.core.proxy.freedom.DestinationOverride parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.v2ray.core.proxy.freedom.DestinationOverride) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.v2ray.core.common.protocol.ServerEndpoint server_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.protocol.ServerEndpoint, com.v2ray.core.common.protocol.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerEndpointOrBuilder> serverBuilder_;
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public boolean hasServer() {
      return serverBuilder_ != null || server_ != null;
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public com.v2ray.core.common.protocol.ServerEndpoint getServer() {
      if (serverBuilder_ == null) {
        return server_ == null ? com.v2ray.core.common.protocol.ServerEndpoint.getDefaultInstance() : server_;
      } else {
        return serverBuilder_.getMessage();
      }
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public Builder setServer(com.v2ray.core.common.protocol.ServerEndpoint value) {
      if (serverBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        server_ = value;
        onChanged();
      } else {
        serverBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public Builder setServer(
        com.v2ray.core.common.protocol.ServerEndpoint.Builder builderForValue) {
      if (serverBuilder_ == null) {
        server_ = builderForValue.build();
        onChanged();
      } else {
        serverBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public Builder mergeServer(com.v2ray.core.common.protocol.ServerEndpoint value) {
      if (serverBuilder_ == null) {
        if (server_ != null) {
          server_ =
            com.v2ray.core.common.protocol.ServerEndpoint.newBuilder(server_).mergeFrom(value).buildPartial();
        } else {
          server_ = value;
        }
        onChanged();
      } else {
        serverBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public Builder clearServer() {
      if (serverBuilder_ == null) {
        server_ = null;
        onChanged();
      } else {
        server_ = null;
        serverBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public com.v2ray.core.common.protocol.ServerEndpoint.Builder getServerBuilder() {
      
      onChanged();
      return getServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    public com.v2ray.core.common.protocol.ServerEndpointOrBuilder getServerOrBuilder() {
      if (serverBuilder_ != null) {
        return serverBuilder_.getMessageOrBuilder();
      } else {
        return server_ == null ?
            com.v2ray.core.common.protocol.ServerEndpoint.getDefaultInstance() : server_;
      }
    }
    /**
     * <code>.v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.protocol.ServerEndpoint, com.v2ray.core.common.protocol.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerEndpointOrBuilder> 
        getServerFieldBuilder() {
      if (serverBuilder_ == null) {
        serverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.v2ray.core.common.protocol.ServerEndpoint, com.v2ray.core.common.protocol.ServerEndpoint.Builder, com.v2ray.core.common.protocol.ServerEndpointOrBuilder>(
                getServer(),
                getParentForChildren(),
                isClean());
        server_ = null;
      }
      return serverBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.freedom.DestinationOverride)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.proxy.freedom.DestinationOverride)
  private static final com.v2ray.core.proxy.freedom.DestinationOverride DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.proxy.freedom.DestinationOverride();
  }

  public static com.v2ray.core.proxy.freedom.DestinationOverride getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DestinationOverride>
      PARSER = new com.google.protobuf.AbstractParser<DestinationOverride>() {
    public DestinationOverride parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DestinationOverride(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DestinationOverride> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DestinationOverride> getParserForType() {
    return PARSER;
  }

  public com.v2ray.core.proxy.freedom.DestinationOverride getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

