// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/common/net/network.proto

package com.v2ray.core.common.net;

public interface NetworkListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.common.net.NetworkList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
   */
  java.util.List<com.v2ray.core.common.net.Network> getNetworkList();
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
   */
  int getNetworkCount();
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
   */
  com.v2ray.core.common.net.Network getNetwork(int index);
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getNetworkValueList();
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 1;</code>
   */
  int getNetworkValue(int index);
}
